version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

  pre_build:
    commands:
      - echo Initializing environment
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
            --domain nextwork \
            --domain-owner 053038338483 \
            --region eu-central-1 \
            --query authorizationToken \
            --output text)
      - echo "Creating Maven settings.xml"
      - |
        cat > settings.xml <<EOF
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                      https://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
            <server>
              <id>nextwork-nextwork-devops-cicd</id>
              <username>aws</username>
              <password>${CODEARTIFACT_AUTH_TOKEN}</password>
            </server>
          </servers>
        </settings>
        EOF
      - echo "settings.xml created with token"

  build:
    commands:
      - echo Build started on `date`
      - mvn -s settings.xml compile

  post_build:
    commands:
      - echo Build completed on `date`
      - mvn -s settings.xml package

artifacts:
  files:
    - target/nextwork-web-project.war
    - appspec.yml
    - scripts/**/*
  discard-paths: no
