version: 0.2

env:
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=/root/.m2/repository"
  parameter-store:
    # Store sensitive values in AWS Systems Manager Parameter Store
    CODEARTIFACT_TOKEN: "/project/codeartifact/token"
    
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Initializing environment
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain nextwork --domain-owner 053038338483 --region eu-central-1 --query authorizationToken --output text`

  build:
    commands:
      - echo Build started on `date`
      - mvn -s settings.xml compile
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn -s settings.xml package
artifacts:
  files:
    - target/nextwork-web-project.war
  discard-paths: no
